version: '3.7'

services:
  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  app:
    build:
      context: ./services/app/
      dockerfile: Dockerfile
    env_file:
      - ./.env.db
    depends_on:
      - "db"
      
volumes:
  postgres_data:

